# Generated by Django 2.1.7 on 2019-04-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='year_pass',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='yop'),
        ),
    ]
