# Generated by Django 2.1.7 on 2019-04-12 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_resume_year_pass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='year_pass',
        ),
    ]
