# Generated by Django 2.1.7 on 2019-04-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0004_resume_educations'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='experiences',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Experiences'),
        ),
    ]
